name: Auth
version: DEV
author: GamakCZ
description: Auth Plugin
main: GamaK\Auth

api:
 - 1.0.0
 - 1.13.0
 - 1.8.0
 - 2.0.0
 
 commands:
 
  login:
   description: login command
   aliases: log
   
  register:
  
  auth:

permissions:
  auth.cmd.help:
   defautl: op
   
